# Generated by Django 5.2.7 on 2025-10-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_question_question_type_studentanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('MA', 'Multiple Answer'), ('SA', 'Short Answer'), ('LA', 'Long Answer')], default='MC', max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
    ]
