# Generated by Django 5.2.7 on 2025-10-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_question_question_type_alter_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('MA', 'Multiple Answer'), ('SA', 'Short Answer'), ('LA', 'Long Answer')], default='MC', max_length=20),
        ),
    ]
